Name:           ros-hydro-pr2-make-a-map-app
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS pr2_make_a_map_app package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/make_a_map
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-gmapping
Requires:       ros-hydro-map-store
Requires:       ros-hydro-pr2-position-scripts
Requires:       ros-hydro-tf
Requires:       ros-hydro-topic-tools
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-gmapping
BuildRequires:  ros-hydro-map-store
BuildRequires:  ros-hydro-pr2-position-scripts
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-topic-tools

%description
Make maps using the PR2 robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Sep 17 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.3-0
- Autogenerated by Bloom

* Tue Sep 16 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

